[package]
name = "ocio-rs"
version = "0.2.1"
edition = "2021"
authors = ["shaloong <contact@shaloong.com>"]
description = "Rust bindings for OpenColorIO v2.5.2"
license = "BSD-3-Clause"
repository = "https://github.com/shaloong/ocio-rs"
documentation = "https://docs.rs/ocio-rs"
keywords = ["opencolorio", "color", "ocio", "vfx", "imaging"]
categories = ["multimedia", "api-bindings"]
readme = "README.md"
exclude = ["tests/data/*", "tests/data/**/*", "third_party/*", "third_party/**/*"]

[dependencies]
ocio-sys = { version = "0.2.1", path = "ocio-sys" }
thiserror = "1.0"

[features]
default = []
bundled = ["ocio-sys/bundled"]

[package.metadata.docs.rs]
no-default-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dev-dependencies]
criterion = "0.5"

[[bench]]
name = "pipeline"
harness = false

[workspace]
members = ["ocio-sys"]
